// API.yaml
openapi: "3.0.0"
info:
  title: Creo Quick Pay API
  version: 1.0.0
  description: API documentation for Creo Quick Pay backend
  contact:
    name: Creo Quick Pay Team
    email: jacquedegraff@creodamo.com
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
