name: Xcode Build and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Select Xcode Version
      run: sudo xcode-select -s '/Applications/Xcode_12.4.app'

    - name: Install Dependencies
      run: |
        xcodebuild -resolvePackageDependencies

    - name: Build
      run: |
        xcodebuild build \
        -project CreoQuickPay.xcodeproj \
        -scheme CreoQuickPayScheme \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 12'

    - name: Run tests
      run: |
        xcodebuild test \
        -project CreoQuickPay.xcodeproj \
        -scheme CreoQuickPayScheme \
        -sdk iphonesimulator \
        -destination 'platform=iOS Simulator,name=iPhone 12'
        
